---
- name: Launch DO master node
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Spin up DO droplet
      digital_ocean: >
          state=present
          command=droplet
          name=masternode
          api_token={{ lookup('env', 'DIGITALOCEAN_ACCESS_TOKEN') }}
          size_id=2gb
          region_id=sfo1
          image_id=ubuntu-14-10-x64
          wait_timeout=500
          ssh_key_ids=321070
      register: master_node
    - name: Print some info about the created master node
      debug: msg="ID is {{ master_node.droplet.id }}, IP is {{ master_node.droplet.ip_address }}"
    - name: Add new droplet to host group
      add_host: hostname={{ master_node.droplet.ip_address }} groups=masters
    - name: Wait for SSH to come up
      wait_for: host={{ master_node.droplet.ip_address }} port=22 delay=60 timeout=320 state=started
    - name: Add newly created server to docker-machine
      command: >
        docker-machine create -d generic
        --generic-ip-address {{ master_node.droplet.ip_address }}
        --swarm
        --swarm-master
        --swarm-discovery token://{{ lookup('env', 'SWARM_TOKEN') }}
        queenbee
