---
- name: Kill created DigitalOcean droplet
  hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Destroy a created DigitalOcean droplet
      digital_ocean: >
          id={{ lookup('env', 'DROPLET_ID') }}
          state=deleted
          command=droplet
          name=masternode
          api_token={{ lookup('env', 'DIGITALOCEAN_ACCESS_TOKEN') }}
